name: Metrics
on:
  # Schedule weekly updates (every Monday at 00:00 UTC)
  schedule:
    - cron: "0 0 * * 1"
  # Allow manual runs and trigger on push to main/master
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions-and-notable.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          # Reactions plugin
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_discussions: 1000
          plugin_reactions_limit_discussions_comments: 1000
          plugin_reactions_details: count
          
          # Notable contributions plugin
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_filter: all
          plugin_notable_indepth: yes
