name: Fetch Merged PRs and Repo Info

on:
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip requests

      - name: Fetch Merged PRs and Repo Info
        run: |
          import requests
          import json

          headers = {"Accept": "application/vnd.github+json"}
          url = "https://api.github.com/search/issues?q=author:hslee2008+type:pr"
          response = requests.get(url, headers=headers)
          data = response.json()

          output = []

          for item in data.get("items", []):
              pr = item.get("pull_request", {})
              if pr.get("merged_at"):
                  pr_url = pr["url"]
                  pr_response = requests.get(pr_url, headers=headers)
                  pr_data = pr_response.json()

                  repo_url = pr_data["base"]["repo"]["url"]
                  repo_html_url = pr_data["base"]["repo"]["html_url"]
                  repo_name = pr_data["base"]["repo"]["name"]
                  org_name = pr_data["base"]["repo"]["owner"]["login"]
                  org_icon = pr_data["base"]["repo"]["owner"]["avatar_url"]

                  repo_meta = requests.get(repo_url, headers=headers).json()
                  stars = repo_meta.get("stargazers_count", 0)

                  output.append({
                      "repo_name": repo_name,
                      "organization": org_name,
                      "organization_icon": org_icon,
                      "stars": stars,
                      "repo_html_url": repo_html_url
                  })

          with open("merged_pr_repos.json", "w") as f:
              json.dump(output, f, indent=2)

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: merged-pr-repos
          path: merged_pr_repos.json
